FROM python:{python_version}-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY worker_entrypoint.py .
ENV PYTHONUNBUFFERED=1
CMD ["python", "worker_entrypoint.py"]
